os: osx
osx_image: xcode10.2
language: swift
xcode_project: "GreenhouseApp.xcodeproj"
xcode_scheme: "GreenhouseApp"
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X

branches:
  only:
  - dev_interface
